### ISSUE TITLE
如果要默认跳转到最后一栏，该用什么方法，求大神指教

### ISSUE THREAD

**Issue by caizhichao** [huang-weilong/flutter_file_manager#2]

**Comment by huang-weilong** [comment]
`controller.jumpTo(controller.position.maxScrollExtent);`
这句可以跳到ListView的最底部。但是前提是ListView已经build完，否则返回的是0。不过这个获取最大值是存在bug的，可能会获取不正确。

**Comment by caizhichao** [comment]
我增加了reserver=treu,shrinkWrap=true两个属性并且将数据反转，并用flexAble包裹得到我想要的效果了，谢谢大神。
