### ISSUE TITLE
文件列表为空

### ISSUE THREAD

**Issue by alylhb** [huang-weilong/flutter_file_manager#5]
没有任何报错, 但是文件列表是空的
![0A19341ACA23E4436B319461D18D347F](https://user-images.githubusercontent.com/38207968/61438791-d8318280-a972-11e9-9102-1bb41cc2f9a8.jpg)

**Comment by huang-weilong** [comment]
确定这不是一个空文件夹？

**Comment by fg2q1q3q** [comment]
我猜可能是因为Android项目清单没有添加权限，所以动态申请权限的时候根本不会提示
