### ISSUE TITLE
打开文件建议添加sdk>=24支持

### ISSUE THREAD

**Issue by axer0910** [huang-weilong/flutter_file_manager#7]
正好在研究怎么打开文件，看了你的文章很有帮助。
直接使用file://形式的uri会报错exposed beyond app through Intent.getData，需要通过FileProvider转为content:// 格式uri才能打开文件
https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/74628980-0b9af080-5192-11ea-9eb7-771b7c82581b.png)
我直接改了这里,试了几个文件都能打开
![image](https://user-images.githubusercontent.com/42160297/74629023-34bb8100-5192-11ea-840f-d2ff824c40de.png)
是因为这个方法获取到的所有path都是不带有file://吗
如果都没有的话是不是 不用FileProvider就直接全部路径都直接前面加上content://就行了

**Comment by huang-weilong** [comment]
在[7199cf4](https://github.com/huang-weilong/flutter_file_manager/commit/7199cf4345874430b1156d838b59889aff07e642)中使用了openfile插件，应该解决了这个问题。
